Make mmj2 work on Cygwin with Windows Java

diff --git a/mmj2jar/mmj2 b/mmj2jar/mmj2
--- a/mmj2jar/mmj2
+++ b/mmj2jar/mmj2
@@ -30,7 +30,7 @@
 # MMJ2_MAXIMUM_MEMORY: Memory minimum (default '1280M')
 
 # You can turn on tracing with:
-# set -x
+set -x
 
 # Enable error detection & give variables default values
 set -eu
@@ -41,9 +41,9 @@ set -eu
 : "${MMJ2_JAR:=""}" # The actual default is based on the script directory
 : "${METAMATH_DB_PATH:=".:$HOME/metamath:$HOME/set.mm:/usr/local/share/metamath::/usr/local/share/set.mm:/usr/share/metamath:/usr/share/set.mm"}"
 
-mm_database='' # Metamath database
+mm_db='' # Metamath database
 proof_file=''  # .mmp file to open
-mmj2_run_commands='' # Filename of mmj2 run commands
+mmj2_run_cmds='' # Filename of mmj2 run commands
 temporary_file=''
 file_naming_last_db="$HOME/.config/mmj2/default_database"
 
@@ -92,8 +92,8 @@ my_realpath () {
 # Handle options.
 while getopts 'd:f:' c ; do
   case "$c" in
-    d) mm_database="$OPTARG" ;;
-    f) mmj2_run_commands="$OPTARG" ;;
+    d) mm_db="$OPTARG" ;;
+    f) mmj2_run_cmds="$OPTARG" ;;
     *) fail "Unknown option $c" ;;
   esac
 done
@@ -107,7 +107,7 @@ fi
 if [ $# = 1 ] ; then
   # Determine what main_file really is.
   case "$1" in
-    (*.mm) mm_database="$1" ;;
+    (*.mm) mm_db="$1" ;;
     (*.mmp)
       # If we've been asked to open a file that doesn't exist, fail fast.
       # This is important because it takes a while for mmj2 to start.
@@ -134,49 +134,49 @@ fi
 # If not given, try to load from default, and if that doesn't work,
 # search for 'set.mm'.
 
-if [ -n "$mm_database" ] ; then # We were given a database name
-  if [ -e "$mm_database" ] && ! [ -d "$mm_database" ] ; then
+if [ -n "$mm_db" ] ; then # We were given a database name
+  if [ -e "$mm_db" ] && ! [ -d "$mm_db" ] ; then
     : # The database we were given exists - we can just use it.
-  elif [ "$mm_database" = "$(basename "$mm_database")" ] ; then
-    new_mm_database="$(search_path "$METAMATH_DB_PATH" "$mm_database")"
-    if ! [ -e "$new_mm_database" ] ; then
-      fail "Could not find $mm_database"
+  elif [ "$mm_db" = "$(basename "$mm_db")" ] ; then
+    new_mm_db="$(search_path "$METAMATH_DB_PATH" "$mm_db")"
+    if ! [ -e "$new_mm_db" ] ; then
+      fail "Could not find $mm_db"
     fi
-    mm_database="$new_mm_database"
+    mm_db="$new_mm_db"
   else
-    fail "Specified database not present: $mm_database"
+    fail "Specified database not present: $mm_db"
   fi
 else # No database specifed, use default (last one) else hunt for it
   if [ -s "$file_naming_last_db" ] ; then
-    mm_database="$(cat "$file_naming_last_db")"
-    echo "Using MM database $mm_database - recorded as default in $mm_database"
+    mm_db="$(cat "$file_naming_last_db")"
+    echo "Using MM database $mm_db - recorded as default in $mm_db"
   else
     # Hunt for metamath database set.mm in $METAMATH_DB_PATH
-    mm_database="$(search_path "$METAMATH_DB_PATH" 'set.mm')"
-    if [ -z "$mm_database" ] ; then
+    mm_db="$(search_path "$METAMATH_DB_PATH" 'set.mm')"
+    if [ -z "$mm_db" ] ; then
       fail 'Cannot find Metamath database set.mm'
     fi
   fi
 fi
 
-if [ -z "$mm_database" ] || ! [ -e "$mm_database" ] ; then
-  fail "Cannot file MM database (e.g., default bad): $mm_database"
+if [ -z "$mm_db" ] || ! [ -e "$mm_db" ] ; then
+  fail "Cannot file MM database (e.g., default bad): $mm_db"
 fi
 
 # Record absolute pathname of database and record for next time.
-mm_database="$(my_realpath "$mm_database")"
+mm_db="$(my_realpath "$mm_db")"
 mkdir -p "$(dirname "$file_naming_last_db")"
-printf '%s' "$mm_database" > "$file_naming_last_db"
-mm_database_basename="$(basename "$mm_database")"
-mm_database_dirname="$(dirname "$mm_database")"
+printf '%s' "$mm_db" > "$file_naming_last_db"
+mm_db_basename="$(basename "$mm_db")"
+mm_db_dirname="$(dirname "$mm_db")"
 
 # Auto-create runcommands unless they were given
-if [ -z "$mmj2_run_commands" ] ; then
+if [ -z "$mmj2_run_cmds" ] ; then
   # Create temporary file & create run commands in it
   command -v mktemp > /dev/null || fail "Command 'mktemp' not found."
   temporary_file="$(mktemp)" # *Securely* create temp file.
   cat > "$temporary_file" <<COMMANDS
-LoadFile,$mm_database_basename
+LoadFile,$mm_db_basename
 VerifyProof,*
 Parse,* 
 ProofAsstUnifySearchExclude,biigb,xxxid,dummylink
@@ -199,12 +199,26 @@ COMMANDS
   fi
   echo 'RunProofAsstGUI' >> "$temporary_file"
 
-  mmj2_run_commands="$temporary_file"
+  mmj2_run_cmds="$temporary_file"
+fi
+
+# If we're running on Cygwin AND the java install is for Windows,
+# convert all filenames to Windows paths using cygpath
+if [ -e /usr/bin/cygpath.exe ] ; then
+  java_location="$(command -v "$JAVA")"
+  case "$java_location" in
+    (/cygdrive/c/Program\ Files*) # Java installed in a *Windows* path
+    # Running on Cygwin, but the Java interpreter expects Windows pathnames
+    [ -z "$mmj2_jar_file" ] || mmj2_jar_file="$(cygpath -w "$mmj2_jar_file")"
+    [ -z "$mmj2_run_cmds" ] || mmj2_run_cmds="$(cygpath -w "$mmj2_run_cmds")"
+    [ -z "$mm_db_dirname" ] || mm_db_dirname="$(cygpath -w "$mm_db_dirname")"
+    ;;
+  esac
 fi
 
 # Actually run mmj2 program!
 "$JAVA" -Xms"$MMJ2_MINIMUM_MEMORY" -Xmx"$MMJ2_MAXIMUM_MEMORY" \
-  -jar "$mmj2_jar_file" "$mmj2_run_commands" Y "" "$mm_database_dirname"
+  -jar "$mmj2_jar_file" "$mmj2_run_cmds" Y "" "$mm_db_dirname"
 
 # Erase temporary file if created
 if [ -n "$temporary_file" ] ; then
